In [2]:
import pandas as pd

In [4]:
data = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/E0.csv")
data

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,...,1.76,0.50,2.09,1.84,2.04,1.88,2.09,1.88,2.03,1.85
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,...,2.73,1.75,1.90,2.03,1.91,2.02,2.01,2.06,1.89,1.99
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,...,1.76,0.50,1.93,2.00,1.93,2.00,1.94,2.04,1.88,2.00
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,...,1.87,-0.25,2.08,1.85,2.10,1.84,2.14,1.87,2.08,1.81
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,...,1.89,-1.00,1.97,1.96,1.99,1.93,2.19,1.97,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,E0,11/02/2023,15:00,Leicester,Tottenham,4,1,H,3,1,...,2.17,0.50,1.85,2.08,1.84,2.10,1.86,2.16,1.82,2.07
215,E0,11/02/2023,15:00,Southampton,Wolves,1,2,A,1,0,...,1.63,0.25,1.83,2.10,1.83,2.11,1.86,2.23,1.81,2.09
216,E0,11/02/2023,17:30,Bournemouth,Newcastle,1,1,D,1,1,...,1.90,1.00,1.77,2.02,1.83,2.11,1.88,2.16,1.80,2.09
217,E0,12/02/2023,14:00,Leeds,Man United,0,2,A,0,0,...,2.26,0.50,1.93,2.00,1.94,1.98,1.94,2.03,1.90,1.98
218,E0,12/02/2023,16:30,Man City,Aston Villa,3,1,H,3,0,...,2.61,-1.75,2.05,1.88,2.10,1.83,2.10,1.90,2.02,1.86

In [5]:
data.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
       'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='object', length=106)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Columns: 106 entries, Div to AvgCAHA
dtypes: float64(82), int64(16), object(8)
memory usage: 181.5+ KB

In [7]:
data.rename(columns={'FTHG': 'Home Goals', 'FTAG': 'Away Goasl'}, inplace=True)
data

,Div,Date,Time,HomeTeam,AwayTeam,Home Goals,Away Goasl,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,...,1.76,0.50,2.09,1.84,2.04,1.88,2.09,1.88,2.03,1.85
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,...,2.73,1.75,1.90,2.03,1.91,2.02,2.01,2.06,1.89,1.99
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,...,1.76,0.50,1.93,2.00,1.93,2.00,1.94,2.04,1.88,2.00
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,...,1.87,-0.25,2.08,1.85,2.10,1.84,2.14,1.87,2.08,1.81
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,...,1.89,-1.00,1.97,1.96,1.99,1.93,2.19,1.97,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,E0,11/02/2023,15:00,Leicester,Tottenham,4,1,H,3,1,...,2.17,0.50,1.85,2.08,1.84,2.10,1.86,2.16,1.82,2.07
215,E0,11/02/2023,15:00,Southampton,Wolves,1,2,A,1,0,...,1.63,0.25,1.83,2.10,1.83,2.11,1.86,2.23,1.81,2.09
216,E0,11/02/2023,17:30,Bournemouth,Newcastle,1,1,D,1,1,...,1.90,1.00,1.77,2.02,1.83,2.11,1.88,2.16,1.80,2.09
217,E0,12/02/2023,14:00,Leeds,Man United,0,2,A,0,0,...,2.26,0.50,1.93,2.00,1.94,1.98,1.94,2.03,1.90,1.98
218,E0,12/02/2023,16:30,Man City,Aston Villa,3,1,H,3,0,...,2.61,-1.75,2.05,1.88,2.10,1.83,2.10,1.90,2.02,1.86